import { Inter } from "next/font/google";
import "./globals.css";

import { GlobalProvider } from "./GlobalProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={inter.className}><GlobalProvider>
      <div className="bg-[#F9F9F9]">
        {children}

        </div>
        
        </GlobalProvider>
        
    
  
        </body>
    </html>
  );
}
